---
- hosts: "{{target}}"
  sudo: yes
  
  vars_files:   
      - ../../../group_vars/local

  tasks:
  - name: Download latest version of the installer
    get_url: url=https://api.bintray.com/packages/bahmni/rpm/bahmni-installer/versions/_latest dest=/tmp url_username={{ wget_username }} url_password={{ wget_password }} 
    
  - name: get the latest installer version
    shell: cat /tmp/_latest | jq '.name' > /tmp/installer_version
    register: cat
    
  - name: Install the installer
#   get_url: url=https://bintray.com/artifact/download/bahmni/rpm/rpms/bahmni-installer-{{ bahmni_installer }}.noarch.rpm dest=/tmp
    yum: name="https://bintray.com/artifact/download/bahmni/rpm/rpms/bahmni-installer-{{ cat }}.noarch.rpm" state=present
