---
- hosts: "{{ target }}"
  sudo: yes

  tasks:
  - name: update yum
    yum: name=* state=latest

  - name: install required packages
    yum: pkg={{ item }} state=installed
    with_items:
        - ntp
        - ntpdate
        - jq # for jason(jason query)
        - vim
        - nano
        - emacs
        - unzip
        - tar
        - wget
        - curl
        - lsb # for hamachi
        - openssh-server # should create handler for this
        - openssh-clients
        - mailx



 # tasks: (can't figure out way user can press enter and input yes)
 # - name: download crashplan
 #   get_url: url=http://download.crashplan.com/installs/linux/install/CrashPlanPRO/CrashPlanPRO_4.5.2_Linux.tgz dest=/tmp

#  - name: Extract crash plan
#    unarchive:  src=/tmp/CrashPlanPRO_4.5.2_Linux.tgz dest=/tmp

#  - name: Run the installation script
#    script: "/tmp/crashplan-install/install.sh < yes"
